platform :ios, '16.0'

project 'App.xcodeproj'
use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
end

def app_pods
  # Local HTTP server for serving game files
  pod 'GCDWebServer', '~> 3.0'
  # ZIP extraction with progress support
  pod 'SSZipArchive', '~> 2.4'
end

target 'App' do
  capacitor_pods
  app_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
